trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildStage
  variables:
    stageVar: BuildStageVar
  jobs:
  - job: BuildStageJob1
    variables: 
      jobVar: BuildJobVar
    steps:
    - bash: echo BuildStageJob1
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(stageVar)
    - bash: echo $(jobVar)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo java -version
    - bash: echo mvn -version
    - bash: echo node --version
    - bash: echo python -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
#   - job: BuildStageJob2
#     steps:
#     - bash: echo BuildStageJob2
#     - bash: echo $(PipelineLevelVariable)
#     - bash: echo $(stageVar)
#     - bash: echo $(jobVar)

# - stage: DevDeployStage
#   dependsOn: BuildStage
#   jobs:
#   - job: DevDeployStageJob
#     steps:
#      - bash: echo DevDeployStageJob

# - stage: QADeployStage
#   dependsOn: BuildStage
#   jobs:
#   - job: QADeployStageJob
#     steps:
#      - bash: echo QADeployStageJob

# - stage: PRDeployStage
#   jobs:
#   - job: PRDeployStageJob
#     steps:
#      - bash: echo PRDeployStageJob
